site_name: nico's homelab docs
site_description: Documentation for nico's homelab
theme:
  name: material
  palette:
      - media: "(prefers-color-scheme)"
        toggle:
          icon: material/link
          name: Switch to light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: indigo
        accent: indigo
        toggle:
          icon: material/toggle-switch
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: black
        accent: indigo
        toggle:
          icon: material/toggle-switch-off
          name: Switch to system preference
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
  color_mode: dark
  favicon: assets/favicon.ico
  font:
    text: Roboto
    code: Roboto Mono

# site_url: https://noranguy.github.io/home-lab/
nav:
  - Home: index.md
  - Overview:
    - Setup: home/setup.md
    - Current Implementations: home/current-implementations.md
    - Planned Implementations: home/planned-implementations.md
  - About: 
    - About: blog/about.md
    - Update Log: blog/update-log.md
    - Struggles: blog/struggles.md
  - Server Setup:
    - Server: server-setup/server-setup.md
    - Nextcloud: server-setup/nextcloud-setup.md
    - Cloudflare: server-setup/cloudflare-setup.md
    - Audiobookshelf: server-setup/audiobookshelf-setup.md
    - Jellyfin: server-setup/jellyfin-setup.md
    - Calibre-Web: server-setup/calibre-web-setup.md
    - Glance: server-setup/glance-setup.md
    - Immich: server-setup/immich-setup.md
    - Nginx Proxy Manager: server-setup/nginx-proxy-manager-setup.md
    - Nicos-Linux-Cheat-Sheet: server-setup/nicos-linux-cheatsheet.md