site_name: nico's homelab docs
theme:
  name: material
  palette:
    primary: 'blue'
    accent: 'dark blue'
    mode: dark
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
  color_mode: dark
  favicon: img/favicon.ico
nav:
  - Home: index.md
  - About: about.md
  - Server Setup: 
    - Server: server-setup.md
    - Nextcloud: nextcloud-setup.md
    - Cloudflare: cloudflare-setup.md